let dict = {
  '웃다':  {eng: 'Laugh', pos: 'verb', for:'action', pic:'laugh'},
  '공원':  {eng: 'Park' , pos: 'noun', for:'place', pic:'park'},
  '대학':  {eng: 'University', pos: 'noun', for: 'place', pic:'uni'},
  '집' :   {eng: 'Home', pos: 'noun', for: 'place', pic:'home'},
  '도서관': {eng: 'Library', pos: 'noun', for: 'place', pic:'library'},
  '식당' : {eng: 'Restaurant', pos: 'noun', for: 'place', pic:'restaurant'},
  '공항' : {eng: 'Airport', pos: 'noun', for: 'place', pic:'airport'},
  '방' :   {eng: 'Room' , pos: 'noun', for: 'place', pic:'room'},
  '화장실': {eng: 'Toilet' , pos: 'noun', for: 'place', pic:'toilet'},
  '은행':   {eng: 'Bank', pos: 'noun', for: 'place', pic:'bank'},
  '수영장':  {eng: 'Swimming pool', pos: 'noun', for: 'place', pic:'swimmingpool'},
  '빵'  :   {eng: 'Bread', pos: 'noun', for: 'food', pic: 'bread'},
  '건물'  :   {eng: 'Building', pos: 'noun', for: 'place', pic:'building'},
  '서점'  :   {eng: 'Book Store', pos: 'noun', for: 'place', pic: 'bookstore'},
  '버터':   {eng: 'Butter', pos: 'noun', for: 'food', pic:'butter'},
  '닭고기': {eng: 'Duck meat', pos: 'noun', for: 'food', pic: 'duckmeat'},
  '고기' :  {eng: 'Meat', pos: 'noun', for: 'food', pic:'meat'},
  '샐러드' : {eng: 'Salad', pos: 'noun', for: 'food', pic:'salad'},
  '샌드위치' : {eng: 'Sandwiches', pos : 'noun', for: 'food', pic: 'sandwiches'},
  '컵' :    {eng: 'Cup', pos: 'noun', for: 'object', pic:'cup'},
  '포크' :  {eng: 'Fork', pos: 'noun', for: 'object', pic:'fork'},
  '노래방' : {eng: 'Karaoke', pos: 'noun', for: 'place', pic:'karaoke'},
  '모자' : {eng: 'Hat', pos: ' noun', for: 'object', pic:'hat'},
  '편지' : {eng: 'Mail', pos: 'noun', for: 'object', pic:'mail'},
  '신문' : {eng: 'Newspaper', pos: 'noun', for: 'object', pic:'newspaper'},
  '구두' : {eng: 'Shoes' , pos: 'noun', for: 'object', pic:'shoes'},
  '말하다' : {eng:'Talk', pos: 'verb', for: 'action', pic:'talk'},
  '쓴다' : {eng: 'Write', pos:'verb', for: 'action', pic:'write'},
 '사랑하다' : {eng: 'Love', pos: 'verb', for: 'action', pic:'love'},
  '주다' : {eng: 'Give', pos: 'verb', for: 'action', pic:'give'},
  '먹다' : {eng: 'Eat', pos: 'verb', for: 'action', pic:'eat'},
  '가다' : {eng: 'Go', pos: 'verb', for: 'action', pic:'go'},
  '노래하다' : {eng: 'Sing', pos: 'verb', for: 'action', pic:'sing'},
  '지하철' : {eng: 'Railway', pos: 'noun', for: 'place', pic: 'railway'},
  '버스' : {eng: 'Bus', pos: 'noun', for: 'place', pic:'bus'}, 
  '손가락' : {eng: 'Finger', pos: 'noun', for: 'object', pic:'finger'}
}
